Module.exports= [
  {
    Title: 'PK',
    Year: '2014',
    Rated: 'Not Rated',
    Released: '19 Dec 2014',
    Runtime: '153 min',
    Genre: 'Comedy, Drama, Sci-Fi',
    Director: 'Rajkumar Hirani',
    Writer: 'Rajkumar Hirani, Abhijat Joshi',
    Actors: 'Aamir Khan, Anushka Sharma, Sanjay Dutt',
    Plot:
      'An alien on Earth loses the only device he can use to communicate with his spaceship. His innocent nature and child-like questions force the country to evaluate the impact of religion on its people.',
    Language: 'Hindi',
    Country: 'India',
    Awards: '20 wins & 22 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTYzOTE2NjkxN15BMl5BanBnXkFtZTgwMDgzMTg0MzE@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.1/10' },
      { Source: 'Rotten Tomatoes', Value: '78%' },
    ],
    Metascore: 'N/A',
    imdbRating: '8.1',
    imdbVotes: '186,817',
    imdbID: 'tt2338151',
    Type: 'movie',
    DVD: '26 Mar 2017',
    BoxOffice: '$10,616,104',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: '3 Idiots',
    Year: '2009',
    Rated: 'PG-13',
    Released: '25 Dec 2009',
    Runtime: '170 min',
    Genre: 'Comedy, Drama',
    Director: 'Rajkumar Hirani',
    Writer: 'Rajkumar Hirani, Abhijat Joshi, Vidhu Vinod Chopra',
    Actors: 'Aamir Khan, Madhavan, Mona Singh',
    Plot:
      'Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently, even as the rest of the world called them "idiots".',
    Language: 'Hindi, English',
    Country: 'India',
    Awards: '63 wins & 28 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNTkyOGVjMGEtNmQzZi00NzFlLTlhOWQtODYyMDc2ZGJmYzFhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.4/10' },
      { Source: 'Rotten Tomatoes', Value: '100%' },
      { Source: 'Metacritic', Value: '67/100' },
    ],
    Metascore: '67',
    imdbRating: '8.4',
    imdbVotes: '396,604',
    imdbID: 'tt1187043',
    Type: 'movie',
    DVD: '26 Apr 2011',
    BoxOffice: '$6,532,874',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Color It Yellow',
    Year: '2006',
    Rated: 'Not Rated',
    Released: '26 Jan 2006',
    Runtime: '167 min',
    Genre: 'Comedy, Crime, Drama',
    Director: 'Rakeysh Omprakash Mehra',
    Writer: "Renzil D'Silva, Prasoon Joshi, Rakeysh Omprakash Mehra",
    Actors: 'Aamir Khan, Soha Ali Khan, Siddharth',
    Plot:
      'The story of six young Indians who assist an English woman to film a documentary on the freedom fighters from their past, and the events that lead them to relive the long-forgotten saga of freedom.',
    Language: 'Hindi',
    Country: 'India',
    Awards: 'Nominated for 1 BAFTA Award49 wins & 46 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BYThmZDA0YmQtMWJhNy00MDQwLTk0Y2YtMDhmZTE5ZjhlNjliXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg',
    Ratings: [{ Source: 'Internet Movie Database', Value: '8.1/10' }],
    Metascore: 'N/A',
    imdbRating: '8.1',
    imdbVotes: '119,080',
    imdbID: 'tt0405508',
    Type: 'movie',
    DVD: '01 Jan 1998',
    BoxOffice: '$2,197,694',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Munna Bhai M.B.B.S.',
    Year: '2003',
    Rated: 'Not Rated',
    Released: '19 Dec 2003',
    Runtime: '2 min',
    Genre: 'Comedy, Drama',
    Director: 'Rajkumar Hirani',
    Writer: 'Vidhu Vinod Chopra, Rajkumar Hirani, Lajan Joseph',
    Actors: 'Sanjay Dutt, Arshad Warsi, Gracy Singh',
    Plot:
      "A gangster sets out to fulfill his father's dream of becoming a doctor.",
    Language: 'Hindi',
    Country: 'India',
    Awards: '26 wins & 36 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMzQ4MTBlYTQtMzJkYS00OGNjLTk1MWYtNzQ0OTQ0OWEyOWU1XkEyXkFqcGdeQXVyNDgyODgxNjE@._V1_SX300.jpg',
    Ratings: [{ Source: 'Internet Movie Database', Value: '8.1/10' }],
    Metascore: 'N/A',
    imdbRating: '8.1',
    imdbVotes: '81,704',
    imdbID: 'tt0374887',
    Type: 'movie',
    DVD: '23 Feb 2004',
    BoxOffice: '$48,772',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Dil Chahta Hai',
    Year: '2001',
    Rated: 'Not Rated',
    Released: '10 Aug 2001',
    Runtime: '183 min',
    Genre: 'Comedy, Drama, Romance',
    Director: 'Farhan Akhtar',
    Writer: 'Kassim Jagmagia, Farhan Akhtar, Karan Vishwanath Kashyap',
    Actors: 'Aamir Khan, Saif Ali Khan, Akshaye Khanna',
    Plot:
      'Three inseparable childhood friends are just out of college. Nothing comes between them - until they each fall in love, and their wildly different approaches to relationships creates tension.',
    Language: 'Hindi',
    Country: 'India',
    Awards: '28 wins & 42 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMjRjMTYwMTYtMmRkNi00MmVkLWE0MjQtNmM3YjI0NWFhZDNmXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg',
    Ratings: [{ Source: 'Internet Movie Database', Value: '8.1/10' }],
    Metascore: 'N/A',
    imdbRating: '8.1',
    imdbVotes: '72,259',
    imdbID: 'tt0292490',
    Type: 'movie',
    DVD: '18 Nov 2016',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Ghajini',
    Year: '2008',
    Rated: 'Not Rated',
    Released: '24 Dec 2008',
    Runtime: '186 min',
    Genre: 'Action, Drama, Mystery',
    Director: 'A.R. Murugadoss',
    Writer: 'Piyush Mishra, A.R. Murugadoss',
    Actors: 'Aamir Khan, Asin Thottumkal, Jiah Khan',
    Plot:
      'A short-term memory loss patient sets out on his journey to avenge the death of his beloved girl.',
    Language: 'Hindi, English, Urdu',
    Country: 'India',
    Awards: '19 wins & 24 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMjU4N2ZlYTktNTFlNy00OGZmLWEwZWQtZDllMjk1MzhiZDEzXkEyXkFqcGdeQXVyODE0NjUxNzY@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '7.3/10' },
      { Source: 'Rotten Tomatoes', Value: '54%' },
    ],
    Metascore: 'N/A',
    imdbRating: '7.3',
    imdbVotes: '61,698',
    imdbID: 'tt1166100',
    Type: 'movie',
    DVD: '28 Dec 2016',
    BoxOffice: '$2,430,627',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Gangs of Wasseypur',
    Year: '2012',
    Rated: 'Not Rated',
    Released: '22 Jun 2012',
    Runtime: '321 min',
    Genre: 'Action, Comedy, Crime',
    Director: 'Anurag Kashyap',
    Writer: 'Akhilesh Jaiswal, Anurag Kashyap, Sachin K. Ladia',
    Actors: 'Manoj Bajpayee, Ashish Chhipa, Richa Chadha',
    Plot:
      'A clash between Sultan and Shahid Khan leads to the expulsion of Khan from Wasseypur, and ignites a deadly blood feud spanning three generations.',
    Language: 'Hindi',
    Country: 'India',
    Awards: '19 wins & 61 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTc5NjY4MjUwNF5BMl5BanBnXkFtZTgwODM3NzM5MzE@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.2/10' },
      { Source: 'Rotten Tomatoes', Value: '97%' },
      { Source: 'Metacritic', Value: '89/100' },
    ],
    Metascore: '89',
    imdbRating: '8.2',
    imdbVotes: '95,699',
    imdbID: 'tt1954470',
    Type: 'movie',
    DVD: '04 Aug 2015',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Dangal',
    Year: '2016',
    Rated: 'Not Rated',
    Released: '21 Dec 2016',
    Runtime: '161 min',
    Genre: 'Action, Biography, Drama',
    Director: 'Nitesh Tiwari',
    Writer: 'Piyush Gupta, Shreyas Jain, Nikhil Mehrotra',
    Actors: 'Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh',
    Plot:
      'Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression.',
    Language: 'Hindi, English',
    Country: 'India, United States',
    Awards: '29 wins & 27 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTQ4MzQzMzM2Nl5BMl5BanBnXkFtZTgwMTQ1NzU3MDI@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.3/10' },
      { Source: 'Rotten Tomatoes', Value: '88%' },
    ],
    Metascore: 'N/A',
    imdbRating: '8.3',
    imdbVotes: '189,482',
    imdbID: 'tt5074352',
    Type: 'movie',
    DVD: '22 Jun 2017',
    BoxOffice: '$12,391,761',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Bajrangi Bhaijaan',
    Year: '2015',
    Rated: 'Not Rated',
    Released: '17 Jul 2015',
    Runtime: '163 min',
    Genre: 'Action, Adventure, Comedy',
    Director: 'Kabir Khan',
    Writer: 'Vijayendra Prasad, Kabir Khan, Parveez Sheikh',
    Actors: 'Salman Khan, Harshaali Malhotra, Nawazuddin Siddiqui',
    Plot:
      'An Indian man with a magnanimous heart takes a young mute Pakistani girl back to her homeland to reunite her with her family.',
    Language: 'Hindi, Urdu',
    Country: 'India',
    Awards: '33 wins & 27 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNGNlYmRmMGEtNWJhYy00ZjMzLWJhOTQtZjdiNTAxMzI5Njg5XkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.1/10' },
      { Source: 'Rotten Tomatoes', Value: '88%' },
    ],
    Metascore: 'N/A',
    imdbRating: '8.1',
    imdbVotes: '87,891',
    imdbID: 'tt3863552',
    Type: 'movie',
    DVD: '16 Jan 2018',
    BoxOffice: '$8,178,001',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Hera Pheri',
    Year: '2000',
    Rated: 'Not Rated',
    Released: '31 Mar 2000',
    Runtime: '156 min',
    Genre: 'Action, Comedy, Crime',
    Director: 'Priyadarshan',
    Writer: 'Siddique, Lal, Neeraj Vora',
    Actors: 'Akshay Kumar, Suniel Shetty, Paresh Rawal',
    Plot:
      'Three unemployed men look for answers to all their money problems - but when their opportunity arrives, will they know what to do with it?',
    Language: 'Hindi',
    Country: 'India',
    Awards: '9 wins & 8 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNDExMTBlZTYtZWMzYi00NmEwLWEzZGYtOTA1MDhmNTc0ODZkXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg',
    Ratings: [{ Source: 'Internet Movie Database', Value: '8.1/10' }],
    Metascore: 'N/A',
    imdbRating: '8.1',
    imdbVotes: '66,743',
    imdbID: 'tt0242519',
    Type: 'movie',
    DVD: '01 Apr 2019',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'My Name Is Khan',
    Year: '2010',
    Rated: 'PG-13',
    Released: '12 Feb 2010',
    Runtime: '165 min',
    Genre: 'Adventure, Drama, Romance',
    Director: 'Karan Johar',
    Writer: 'Shibani Bathija, Niranjan Iyengar',
    Actors: 'Shah Rukh Khan, Kajol, Sheetal Menon',
    Plot:
      "An Indian Muslim man with Asperger's syndrome takes a challenge to speak to the President of the United States seriously and embarks on a cross-country journey.",
    Language: 'Hindi, English',
    Country: 'India, United Arab Emirates, United States',
    Awards: '25 wins & 32 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTUyMTA4NDYzMV5BMl5BanBnXkFtZTcwMjk5MzcxMw@@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '7.9/10' },
      { Source: 'Rotten Tomatoes', Value: '83%' },
      { Source: 'Metacritic', Value: '50/100' },
    ],
    Metascore: '50',
    imdbRating: '7.9',
    imdbVotes: '107,150',
    imdbID: 'tt1188996',
    Type: 'movie',
    DVD: '10 Aug 2010',
    BoxOffice: '$4,018,771',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Barfi!',
    Year: '2012',
    Rated: 'Not Rated',
    Released: '14 Sep 2012',
    Runtime: '151 min',
    Genre: 'Comedy, Drama, Romance',
    Director: 'Anurag Basu',
    Writer: 'Anurag Basu, Tani Basu, Sanjeev Dutta',
    Actors: "Ranbir Kapoor, Priyanka Chopra Jonas, Ileana D'Cruz",
    Plot:
      "Three young people learn that love can neither be defined nor contained by society's definition of normal and abnormal.",
    Language: 'Hindi',
    Country: 'India',
    Awards: '61 wins & 33 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTQzMTEyODY2Ml5BMl5BanBnXkFtZTgwMjA0MDUyMjE@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.1/10' },
      { Source: 'Rotten Tomatoes', Value: '86%' },
    ],
    Metascore: 'N/A',
    imdbRating: '8.1',
    imdbVotes: '82,007',
    imdbID: 'tt2082197',
    Type: 'movie',
    DVD: '11 Mar 2017',
    BoxOffice: '$2,804,874',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Dilwale Dulhania Le Jayenge',
    Year: '1995',
    Rated: 'Not Rated',
    Released: '20 Oct 1995',
    Runtime: '181 min',
    Genre: 'Drama, Romance',
    Director: 'Aditya Chopra',
    Writer: 'Aditya Chopra, Javed Siddiqui',
    Actors: 'Shah Rukh Khan, Kajol, Amrish Puri',
    Plot:
      "When Raj meets Simran in Europe, it isn't love at first sight but when Simran moves to India for an arranged marriage, love makes its presence felt.",
    Language: 'Punjabi, Urdu',
    Country: 'India',
    Awards: '15 wins & 3 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMDQ2ZmE2NTMtZDE3NC00YzFjLWJhNmEtMDEzMTI5ZjU2ZGM0XkEyXkFqcGdeQXVyNTkzNDQ4ODc@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.0/10' },
      { Source: 'Rotten Tomatoes', Value: '100%' },
    ],
    Metascore: 'N/A',
    imdbRating: '8.0',
    imdbVotes: '69,571',
    imdbID: 'tt0112870',
    Type: 'movie',
    DVD: '23 Mar 2017',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'OMG: Oh My God!',
    Year: '2012',
    Rated: 'Not Rated',
    Released: '28 Sep 2012',
    Runtime: '125 min',
    Genre: 'Comedy, Drama, Fantasy',
    Director: 'Umesh Shukla',
    Writer: 'Alok Jha, Saumya Joshi, Bhavesh Mandalia',
    Actors: 'Paresh Rawal, Akshay Kumar, Mithun Chakraborty',
    Plot:
      'A shopkeeper takes God to court when his shop is destroyed by an earthquake.',
    Language: 'Hindi, English',
    Country: 'India',
    Awards: '6 wins & 12 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMGNhYjUwNmYtNDQxNi00NDdmLTljMDAtZWM1NDQyZTk3ZDYwXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg',
    Ratings: [{ Source: 'Internet Movie Database', Value: '8.1/10' }],
    Metascore: 'N/A',
    imdbRating: '8.1',
    imdbVotes: '58,748',
    imdbID: 'tt2283748',
    Type: 'movie',
    DVD: '17 Mar 2017',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Bhaag Milkha Bhaag',
    Year: '2013',
    Rated: 'Not Rated',
    Released: '12 Jul 2013',
    Runtime: '3 min',
    Genre: 'Biography, Drama, Sport',
    Director: 'Rakeysh Omprakash Mehra',
    Writer: 'Prasoon Joshi',
    Actors: 'Farhan Akhtar, Japtej Singh, Divya Dutta',
    Plot:
      'The truth behind the ascension of Milkha Singh, who was scarred by of the India-Pakistan partition.',
    Language: 'Hindi',
    Country: 'India',
    Awards: '52 wins & 45 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTY1Nzg4MjcwN15BMl5BanBnXkFtZTcwOTc1NTk1OQ@@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.2/10' },
      { Source: 'Rotten Tomatoes', Value: '74%' },
    ],
    Metascore: 'N/A',
    imdbRating: '8.2',
    imdbVotes: '67,734',
    imdbID: 'tt2356180',
    Type: 'movie',
    DVD: '21 May 2017',
    BoxOffice: '$1,636,731',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Secret Superstar',
    Year: '2017',
    Rated: 'Not Rated',
    Released: '18 Oct 2017',
    Runtime: '150 min',
    Genre: 'Drama, Music',
    Director: 'Advait Chandan',
    Writer: 'Advait Chandan',
    Actors: 'Zaira Wasim, Meher Vij, Raj Arjun',
    Plot:
      'A talented teenage singer-songwriter living amid domestic abuse becomes a YouTube sensation after a video in which she hides her identity goes viral.',
    Language: 'Hindi',
    Country: 'India',
    Awards: '14 wins & 21 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BM2IzMGIxMDQtNzE3OS00MGZjLTljNzgtMGE2MjAyZThmNjNhXkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '7.8/10' },
      { Source: 'Rotten Tomatoes', Value: '92%' },
    ],
    Metascore: 'N/A',
    imdbRating: '7.8',
    imdbVotes: '26,266',
    imdbID: 'tt6108090',
    Type: 'movie',
    DVD: '24 Mar 2018',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Andhadhun',
    Year: '2018',
    Rated: 'Not Rated',
    Released: '05 Oct 2018',
    Runtime: '139 min',
    Genre: 'Comedy, Crime, Music',
    Director: 'Sriram Raghavan',
    Writer: 'Arijit Biswas, Yogesh Chandekar, Sriram Raghavan',
    Actors: 'Ayushmann Khurrana, Tabu, Radhika Apte',
    Plot:
      'A series of mysterious events change the life of a blind pianist, who must now report a crime that he should technically know nothing of.',
    Language: 'Hindi, English',
    Country: 'India',
    Awards: '33 wins & 29 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZWZhMjhhZmYtOTIzOC00MGYzLWI1OGYtM2ZkN2IxNTI4ZWI3XkEyXkFqcGdeQXVyNDAzNDk0MTQ@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.2/10' },
      { Source: 'Rotten Tomatoes', Value: '100%' },
    ],
    Metascore: 'N/A',
    imdbRating: '8.2',
    imdbVotes: '92,037',
    imdbID: 'tt8108198',
    Type: 'movie',
    DVD: '16 Dec 2018',
    BoxOffice: '$1,193,046',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Baahubali 2: The Conclusion',
    Year: '2017',
    Rated: 'Not Rated',
    Released: '28 Apr 2017',
    Runtime: '167 min',
    Genre: 'Action, Drama',
    Director: 'S.S. Rajamouli',
    Writer: 'Vijayendra Prasad, S.S. Rajamouli, C.H. Vijay Kumar',
    Actors: 'Prabhas, Rana Daggubati, Anushka Shetty',
    Plot:
      'When Shiva, the son of Bahubali, learns about his heritage, he begins to look for answers. His story is juxtaposed with past events that unfolded in the Mahishmati Kingdom.',
    Language: 'Telugu, Tamil, Hindi',
    Country: 'India',
    Awards: '28 wins & 15 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BOGNlNmRkMjctNDgxMC00NzFhLWIzY2YtZDk3ZDE0NWZhZDBlXkEyXkFqcGdeQXVyODIwMDI1NjM@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.2/10' },
      { Source: 'Rotten Tomatoes', Value: '87%' },
    ],
    Metascore: 'N/A',
    imdbRating: '8.2',
    imdbVotes: '99,089',
    imdbID: 'tt4849438',
    Type: 'movie',
    DVD: '03 Aug 2017',
    BoxOffice: '$20,186,659',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Gully Boy',
    Year: '2019',
    Rated: 'Not Rated',
    Released: '14 Feb 2019',
    Runtime: '154 min',
    Genre: 'Drama, Music, Romance',
    Director: 'Zoya Akhtar',
    Writer: 'Zoya Akhtar, Reema Kagti, Vijay Maurya',
    Actors: 'Ranveer Singh, Alia Bhatt, Siddhant Chaturvedi',
    Plot:
      'A coming-of-age story based on the lives of street rappers in Mumbai.',
    Language: 'Hindi, English',
    Country: 'India',
    Awards: '68 wins & 55 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZDkzMTQ1YTMtMWY4Ny00MzExLTkzYzEtNzZhOTczNzU2NTU1XkEyXkFqcGdeQXVyODY3NjMyMDU@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '7.9/10' },
      { Source: 'Rotten Tomatoes', Value: '96%' },
      { Source: 'Metacritic', Value: '65/100' },
    ],
    Metascore: '65',
    imdbRating: '7.9',
    imdbVotes: '39,313',
    imdbID: 'tt2395469',
    Type: 'movie',
    DVD: '18 Apr 2019',
    BoxOffice: '$5,566,534',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Uri: The Surgical Strike',
    Year: '2019',
    Rated: 'Not Rated',
    Released: '11 Jan 2019',
    Runtime: '138 min',
    Genre: 'Action, Drama, History',
    Director: 'Aditya Dhar',
    Writer: 'Aditya Dhar',
    Actors: 'Vicky Kaushal, Paresh Rawal, Mohit Raina',
    Plot:
      'Indian army special forces execute a covert operation, avenging the killing of fellow army men at their base by a terrorist group.',
    Language: 'Hindi',
    Country: 'India',
    Awards: '19 wins & 25 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMWU4ZjNlNTQtOGE2MS00NDI0LWFlYjMtMmY3ZWVkMjJkNGRmXkEyXkFqcGdeQXVyNjE1OTQ0NjA@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.2/10' },
      { Source: 'Rotten Tomatoes', Value: '62%' },
    ],
    Metascore: 'N/A',
    imdbRating: '8.2',
    imdbVotes: '62,936',
    imdbID: 'tt8291224',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$4,186,168',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Zindagi Na Milegi Dobara',
    Year: '2011',
    Rated: 'Not Rated',
    Released: '15 Jul 2011',
    Runtime: '155 min',
    Genre: 'Comedy, Drama, Musical',
    Director: 'Zoya Akhtar',
    Writer: 'Farhan Akhtar, Reema Kagti, Zoya Akhtar',
    Actors: 'Hrithik Roshan, Farhan Akhtar, Abhay Deol',
    Plot:
      'Three friends decide to turn their fantasy vacation into reality after one of their friends gets engaged.',
    Language: 'Hindi, English, Spanish',
    Country: 'India',
    Awards: '35 wins & 31 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZGFmMjM5OWMtZTRiNC00ODhlLThlYTItYTcyZDMyYmMyYjFjXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.2/10' },
      { Source: 'Rotten Tomatoes', Value: '93%' },
    ],
    Metascore: 'N/A',
    imdbRating: '8.2',
    imdbVotes: '77,981',
    imdbID: 'tt1562872',
    Type: 'movie',
    DVD: '30 Nov 2016',
    BoxOffice: '$3,108,485',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Kal Ho Naa Ho',
    Year: '2003',
    Rated: 'Not Rated',
    Released: '28 Nov 2003',
    Runtime: '2 min',
    Genre: 'Comedy, Drama, Musical',
    Director: 'Nikkhil Advani',
    Writer: 'Niranjan Iyengar, Karan Johar',
    Actors: 'Preity Zinta, Shah Rukh Khan, Saif Ali Khan',
    Plot:
      "Naina, an introverted, perpetually depressed girl's life changes when she meets Aman. But Aman has a secret of his own which changes their lives forever. Embroiled in all this is Rohit, Naina's best friend who conceals his love fo...",
    Language: 'Hindi, English',
    Country: 'India',
    Awards: '45 wins & 46 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BYmVjNDIxODAtNWZiZi00ZDBlLWJmOTUtNDNjMGExNTViMzE1XkEyXkFqcGdeQXVyNTE0MDc0NTM@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '7.9/10' },
      { Source: 'Rotten Tomatoes', Value: '70%' },
      { Source: 'Metacritic', Value: '54/100' },
    ],
    Metascore: '54',
    imdbRating: '7.9',
    imdbVotes: '69,153',
    imdbID: 'tt0347304',
    Type: 'movie',
    DVD: '10 Aug 2004',
    BoxOffice: '$1,991,922',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'A Wednesday',
    Year: '2008',
    Rated: 'Not Rated',
    Released: '05 Sep 2008',
    Runtime: '1 min',
    Genre: 'Action, Crime, Drama',
    Director: 'Neeraj Pandey',
    Writer: 'Neeraj Pandey',
    Actors: 'Anupam Kher, Naseeruddin Shah, Veerendra Saxena',
    Plot:
      'A retiring police officer reminisces about the most astounding day of his career. About a case that was never filed but continues to haunt him in his memories - the case of a man and a Wednesday.',
    Language: 'Urdu, Hindi',
    Country: 'India',
    Awards: '10 wins & 19 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BOTcwMzdiMWItMjZlOS00MzAzLTg5OTItNTA4OGYyMjBhMmRiXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg',
    Ratings: [{ Source: 'Internet Movie Database', Value: '8.1/10' }],
    Metascore: 'N/A',
    imdbRating: '8.1',
    imdbVotes: '78,472',
    imdbID: 'tt1280558',
    Type: 'movie',
    DVD: '26 Mar 2017',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Sanju',
    Year: '2018',
    Rated: 'TV-MA',
    Released: '29 Jun 2018',
    Runtime: '155 min',
    Genre: 'Biography, Comedy, Drama',
    Director: 'Rajkumar Hirani',
    Writer: 'Abhiruchi Chand, Rajkumar Hirani, Abhijat Joshi',
    Actors: 'Ranbir Kapoor, Paresh Rawal, Manisha Koirala',
    Plot:
      'Biopic of the controversial life of actor Sanjay Dutt: his film career, jail sentence, and personal life.',
    Language: 'Hindi',
    Country: 'India',
    Awards: '13 wins & 27 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMjI3NTM1NzMyNF5BMl5BanBnXkFtZTgwOTE4NTgzNTM@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '7.6/10' },
      { Source: 'Rotten Tomatoes', Value: '44%' },
    ],
    Metascore: 'N/A',
    imdbRating: '7.6',
    imdbVotes: '54,669',
    imdbID: 'tt6452574',
    Type: 'movie',
    DVD: '15 Oct 2018',
    BoxOffice: '$7,909,317',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Pink',
    Year: '2016',
    Rated: 'Not Rated',
    Released: '16 Sep 2016',
    Runtime: '2 min',
    Genre: 'Crime, Drama, Thriller',
    Director: 'Aniruddha Roy Chowdhury',
    Writer: 'Shoojit Sircar, Aniruddha Roy Chowdhury, Ritesh Shah',
    Actors: 'Amitabh Bachchan, Taapsee Pannu, Kirti Kulhari',
    Plot:
      'When three young women are implicated in a crime, a retired lawyer steps forward to help them clear their names.',
    Language: 'Hindi',
    Country: 'India',
    Awards: '20 wins & 26 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNGI1MTI1YTQtY2QwYi00YzUzLTg3NWYtNzExZDlhOTZmZWU0XkEyXkFqcGdeQXVyMDkwNTkwNg@@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.1/10' },
      { Source: 'Rotten Tomatoes', Value: '100%' },
    ],
    Metascore: 'N/A',
    imdbRating: '8.1',
    imdbVotes: '45,023',
    imdbID: 'tt5571734',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Baahubali: The Beginning',
    Year: '2015',
    Rated: 'Not Rated',
    Released: '09 Jul 2015',
    Runtime: '159 min',
    Genre: 'Action, Drama',
    Director: 'S.S. Rajamouli',
    Writer: 'Vijayendra Prasad, S.S. Rajamouli, C.H. Vijay Kumar',
    Actors: 'Prabhas, Rana Daggubati, Anushka Shetty',
    Plot:
      'In ancient India, an adventurous and daring man becomes involved in a decades-old feud between two warring peoples.',
    Language: 'Telugu, Tamil',
    Country: 'India',
    Awards: '54 wins & 22 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BYWVlMjVhZWYtNWViNC00ODFkLTk1MmItYjU1MDY5ZDdhMTU3XkEyXkFqcGdeQXVyODIwMDI1NjM@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.0/10' },
      { Source: 'Rotten Tomatoes', Value: '90%' },
    ],
    Metascore: 'N/A',
    imdbRating: '8.0',
    imdbVotes: '123,327',
    imdbID: 'tt2631186',
    Type: 'movie',
    DVD: '18 Aug 2016',
    BoxOffice: '$6,738,000',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Chhichhore',
    Year: '2019',
    Rated: 'Not Rated',
    Released: '06 Sep 2019',
    Runtime: '143 min',
    Genre: 'Comedy, Drama, Romance',
    Director: 'Nitesh Tiwari',
    Writer: 'Piyush Gupta, Nikhil Mehrotra, Nitesh Tiwari',
    Actors: 'Sushant Singh Rajput, Shraddha Kapoor, Varun Sharma',
    Plot:
      'A tragic incident forces Anirudh, a middle-aged man, to take a trip down memory lane and reminisce his college days along with his friends, who were labelled as losers.',
    Language: 'Hindi',
    Country: 'India',
    Awards: '4 wins & 14 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BYjg2ZDI2YTYtN2EwYi00YWI5LTgyMWQtMWFkYmE3NmJkOGVhXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.3/10' },
      { Source: 'Rotten Tomatoes', Value: '58%' },
    ],
    Metascore: 'N/A',
    imdbRating: '8.3',
    imdbVotes: '53,401',
    imdbID: 'tt9052870',
    Type: 'movie',
    DVD: '19 Nov 2020',
    BoxOffice: '$2,004,400',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Hindi Medium',
    Year: '2017',
    Rated: 'Not Rated',
    Released: '19 May 2017',
    Runtime: '2 min',
    Genre: 'Comedy, Drama',
    Director: 'Saket Chaudhary',
    Writer: 'Sonu Sinha, Saket Chaudhary, Amitosh Nagpal',
    Actors: 'Irrfan Khan, Saba Qamar, Dishita Sehgal',
    Plot:
      'A couple from Chandni Chowk aspire to give their daughter the best education and thus be a part of and accepted by the elite of Delhi.',
    Language: 'Hindi',
    Country: 'India',
    Awards: '6 wins & 16 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BY2E4NWQ4ZjEtNThlOC00NThjLThmZjgtMWU0MDgzMmYwOGU3XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '7.8/10' },
      { Source: 'Rotten Tomatoes', Value: '82%' },
    ],
    Metascore: 'N/A',
    imdbRating: '7.8',
    imdbVotes: '28,893',
    imdbID: 'tt5764096',
    Type: 'movie',
    DVD: '16 Jan 2018',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Chennai Express',
    Year: '2013',
    Rated: 'Not Rated',
    Released: '08 Aug 2013',
    Runtime: '2 min',
    Genre: 'Action, Comedy, Romance',
    Director: 'Rohit Shetty',
    Writer: 'K. Subhash, Yunus Sajawal, Robin Bhatt',
    Actors: 'Deepika Padukone, Shah Rukh Khan, Sathyaraj',
    Plot:
      "A man heading towards Rameshwaram via Chennai express to immerse his late grandfather's ashes unwillingly gets caught amidst goons after helping their boss's daughter and them board the train.",
    Language: 'Hindi, Tamil, English, Marathi',
    Country: 'India',
    Awards: '32 wins & 55 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZGFmMzQwNzEtZTIwNy00Nzc4LTk1YzEtYWFmNWUxZDYwODcwL2ltYWdlXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '6.0/10' },
      { Source: 'Rotten Tomatoes', Value: '47%' },
      { Source: 'Metacritic', Value: '45/100' },
    ],
    Metascore: '45',
    imdbRating: '6.0',
    imdbVotes: '54,612',
    imdbID: 'tt2112124',
    Type: 'movie',
    DVD: '11 Mar 2017',
    BoxOffice: '$5,307,960',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'M.S. Dhoni: The Untold Story',
    Year: '2016',
    Rated: 'Not Rated',
    Released: '30 Sep 2016',
    Runtime: '184 min',
    Genre: 'Biography, Drama, Sport',
    Director: 'Neeraj Pandey',
    Writer: 'Neeraj Pandey, Dilip Jha, Mohinder Pratap Singh',
    Actors: 'Sushant Singh Rajput, Kiara Advani, Anupam Kher',
    Plot:
      "The untold story of Mahendra Singh Dhoni's journey from ticket collector to trophy collector - the world-cup-winning captain of the Indian Cricket Team.",
    Language: 'Hindi',
    Country: 'India',
    Awards: '8 wins & 20 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZjAzZjZiMmQtMDZmOC00NjVmLTkyNTItOGI2Mzg4NTBhZTA1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '7.9/10' },
      { Source: 'Rotten Tomatoes', Value: '75%' },
    ],
    Metascore: 'N/A',
    imdbRating: '7.9',
    imdbVotes: '57,317',
    imdbID: 'tt4169250',
    Type: 'movie',
    DVD: '23 May 2017',
    BoxOffice: '$1,801,550',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
];
